wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1680714192.580647
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.11
      5: 0.13.10
      8:
      - 3
      - 5
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.005
number_of_client:
  desc: null
  value: 20
